import airbnb from "./photos/airbnb.png";
import amazon from "./photos/amazon.webp";
import fb from "./photos/fb.webp";
import google from "./photos/google.png";
import microsoft from "./photos/microsoft.png";
import netflix from "./photos/netflix.jpg";
import twitter from "./photos/twitter.png";
import apple from "./photos/apple.jpg";
import yt from "./photos/yt.webp";
import linkedin from "./photos/linkedin.webp";

export const jobData = [
  {
    id: 1,
    logo: microsoft,
    position: "Frontend Developer",
    company: "Microsoft",
    city: "Częstochowa",
    fullyRemote: true,
    friendly: false,
    salary: "Undisclosed Salary",
    technologies: ["JS", "React", "HTML", "CSS"],
    date_added: "2024-02-08",
  },
  {
    id: 2,
    logo: google,
    position: "Backend Developer",
    company: "Google",
    city: "Opole",
    fullyRemote: true,
    friendly: false,
    salary: "$90,000 - $110,000",
    technologies: ["Python", "Django", "Java", "Spring"],
    date_added: "2024-02-15",
  },
  {
    id: 3,
    logo: amazon,
    position: "Data Scientist",
    company: "Amazon",
    city: "Sydney",
    fullyRemote: false,
    friendly: true,
    salary: "$100,000 - $120,000",
    technologies: ["Python", "R", "SQL", "Machine Learning"],
    date_added: "2024-02-14",
  },
  {
    id: 4,
    logo: apple,
    position: "UI/UX Designer",
    company: "Apple",
    city: "Poznań",
    fullyRemote: false,
    friendly: false,
    salary: "$85,000 - $105,000",
    technologies: ["Adobe XD", "Sketch", "Figma"],
    date_added: "2024-02-04",
  },
  {
    id: 5,
    logo: fb,
    position: "Software Engineer",
    company: "Facebook",
    city: "Zielona Góra",
    fullyRemote: false,
    friendly: true,
    salary: "Undisclosed Salary",
    technologies: ["JS", "React", "Node.js", "MongoDB"],
    date_added: "2024-02-06",
  },

  {
    id: 6,
    logo: yt,
    position: "Mobile App Developer",
    company: "Youtube",
    city: "San Francisco",
    fullyRemote: false,
    friendly: true,
    salary: "$90,000 - $110,000",
    technologies: ["Swift", "Kotlin", "React Native"],
    date_added: "2024-02-06",
  },
  {
    id: 7,
    logo: netflix,
    position: "DevOps Engineer",
    company: "Netflix",
    city: "Warszawa",
    fullyRemote: true,
    friendly: true,
    salary: "$100,000 - $120,000",
    technologies: ["Docker", "Kubernetes", "AWS", "Terraform"],
    date_added: "2024-02-18",
  },
  {
    id: 8,
    logo: linkedin,
    position: "Data Engineer",
    company: "LinkedIn",
    city: "Śląsk",
    fullyRemote: true,
    friendly: false,
    salary: "$95,000 - $115,000",
    technologies: ["SQL", "Spark", "Hadoop", "Airflow"],
    date_added: "2024-02-01",
  },
  {
    id: 9,
    logo: twitter,
    position: "Product Manager",
    company: "Twitter",
    city: "Lublin",
    fullyRemote: false,
    friendly: true,
    salary: "$110,000 - $130,000",
    technologies: ["Agile", "Scrum", "Product Management"],
    date_added: "2024-02-14",
  },
  {
    id: 10,
    logo: airbnb,
    position: "Quality Assurance Engineer",
    company: "Airbnb",
    city: "London",
    fullyRemote: true,
    friendly: true,
    salary: "$80,000 - $100,000",
    technologies: ["Selenium", "JUnit", "TestNG", "CI/CD"],
    date_added: "2024-02-07",
  },
];
